apiVersion: v1
kind: ConfigMap
metadata:
  name: api-gateway-config
  namespace: drgueria
data:
  PORT: "4000"
  MS_USUARIOS_URL: "http://ms-usuarios-svc:3000"
  MS_PRODUCTOS_URL: "http://ms-productos-svc:3001"
  MS_PROVEEDORES_URL: "http://ms-proveedores-svc:3002"
  MS_NOTIFICACIONES_URL: "http://ms-notificaciones-svc:3005"
  NODE_ENV: "production"