apiVersion: v1
kind: Secret
metadata:
  name: ms-usuarios-secret
  namespace: drgueria
type: Opaque
data:
  DB_USER: cm9vdA==
  DB_PASSWORD: ZHJndWVyaWEyMDI0
  JWT_SECRET: ZHJndWVyaWFfc2VjcmV0b18yMDI0
