apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
  namespace: drgueria
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api-gateway
  template:
    metadata:
      labels:
        app: api-gateway
    spec:
      terminationGracePeriodSeconds: 30
      containers:
      - name: api-gateway
        image: drgueria/api-gateway:latest
        ports:
        - containerPort: 4000
        envFrom:
        - configMapRef:
            name: api-gateway-config
        livenessProbe:
          httpGet:
            path: /
            port: 4000
          initialDelaySeconds: 15
          periodSeconds: 20
        readinessProbe:
          httpGet:
            path: /
            port: 4000
          initialDelaySeconds: 5
          periodSeconds: 10
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"